rpc:
  enable: true
  bind: :8080
remote_mode: false
server_addr: http://localhost:8081
jwt_token: ""
debug: true
interval: 20
out_put_path: ./
ffmpeg_path: ""
log:
  out_put_folder: ./
  save_last_log: true
  save_every_log: false
feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false
live_rooms:
- url: https://www.lang.live/room/5664344
  is_listening: false
  quality: 0
  audio_only: false
- url: https://live.bilibili.com/22603245
  is_listening: true
  quality: 0 
# '{{ .Live.GetPlatformCNName }}/{{ .HostName | filenameFilter }}/[{{ now | date "2006-01-02 15-04-05"}}][{{ .HostName | filenameFilter }}][{{ .RoomName | filenameFilter }}].flv'
# ./平台名称/主播名字/[时间戳][主播名字][房间名字].flv
# https://github.com/bililive-go/bililive-go/wiki/More-Tips
out_put_tmpl: ''
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0
cookies:
  live.bilibili.com: a=1;b=2
on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""
timeout_in_us: 60000000
